language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
env:
  global:
  - GIT_REPO: github.com/jumpbyte/jumpbyte.github.io.git
  - CODING_REPO: git.coding.net/jumpbyte/jumpbyte.git
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_fca23b2cf72d_key -iv $encrypted_fca23b2cf72d_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'jumpbyte'
- git config --global user.email '920293408@qq.com'
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo g
- hexo d
