language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
env:
  global:
   - GIT_REPO: github.com/jumpbyte/jumpbyte.github.io.git
cache:
  directories:
  - node_modules
after_script:
- cd ./public
- git config --global user.name 'jumpbyte'
- git config --global user.email 920293408@qq.com
- git add .
- git commit -m "Update docs"
- git push --force --quiet "https://${REPO_TOKEN}@${GIT_REPO}" master:master
install:
- npm install hexo-cli -g
- npm install
script:
- hexo g
