language: node_js

sudo: false

node_js:
  - '4'

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_e96b7e298bd3_key -iv $encrypted_e96b7e298bd3_iv -in .travis/travis_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'jumpbyte'
- git config --global user.email 920293408@qq.com

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy